In [2]:
import pandas as pd
import os
tiles = pd.read_csv(os.path.join('..','maps','training.csv'),header=None)
tiles.head()

   0  1  2  3  4  5  6  7     8
0  c  c  c  c  c  c  c  c  none
1  c  c  c  c  c  c  c  c  none
2  c  c  c  c  c  g  c  c  none
3  c  c  c  c  c  g  g  c  none
4  c  c  c  c  c  g  g  g  none

In [3]:
patterns = {}

for index, row in tiles.iterrows():
    nbhr = ''.join(row[0:-1])
    label = row[8]
    if nbhr in patterns:
        if patterns[nbhr] != label:
            print('Inconsistent pattern')
    else:
        patterns[nbhr] = label
        
for pattern in patterns:
    print(pattern,patterns[pattern])

cccccccc none
cccccgcc none
cccccggc none
cccccggg none
ccccccgg none
ccccwccg wl
gccwcccg wbbl
ccwwwwcc wctr
cccwwwwc wcbr
ggcccwcg wbtl
ggccwwcc wl
cgcwwwww wcbr
cggccwwc wt
ggggcwcc wbtl
cgccwwww wcbr
cggccwww wt
cgggcwww wt
cgggcwwc wt
ggggcwcg wbtl
cgcwwwcc wl
gggccccg none
ggcccccg none
cccwwwcc wl
ggcccwcc wbtl
ccgccwww wt
wwcgcwww wcbl
wccggccw wr
cccgggcw wbtr
cgggggcc none
ggggcccc none
cgccccwc wt
gggccwcc wbtl
cgccwwcc wl
cccwwccc wl
ggcccggg none
cccwccgg wbbl
ccwwwwcg wctr
gccwwwcg wl
ggcwwwcc wl
cgccwccc wl
cggccccc none
cgggcccc none
ccggcccc none
cccgcccc none
cccggccc none
cccgggcc none
ccccggcc none
ccccgggc none
cccggggg none

In [5]:
import json
with open('patterns.json', 'w') as fp:
    json.dump(patterns, fp)

In [13]:
with open('patterns.csv', 'w') as f: 
    for pattern in patterns:
        f.write(pattern+','+patterns[pattern]+'\n')